crop_size:
  - 128

batch_size:
  - 64
  - 128

num_epochs:
  - 100
  - 200

learning_rate:
  - 0.0005
  - 0.0001
  - 0.001

num_imgs:
  - -1
  - 64

regularize:
  - 0.0
  - 0.001

train_split:
  - 0.8
